[package]
name = "run-aoc"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
aoc-proc = { path = "../aoc-proc" }
cookie = "0.16.2"
cookie_store = "0.19.0"
dirs = "4.0.0"
lazy_static = "1.4.0"
nom = "7.1.3"
regex = "1.7.1"
ureq = { version = "2.6.1", features = ["cookies"] }
url = "2.3.1"
