[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
nom = "7.1.1"
run-aoc = { path = "crates/run-aoc" }
seq-macro = "0.3.2"
